// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: gateway.proto

package gatwaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BDNSGateway_SubscribeHeaders_FullMethodName = "/gateway.BDNSGateway/SubscribeHeaders"
	BDNSGateway_QueryDomain_FullMethodName      = "/gateway.BDNSGateway/QueryDomain"
	BDNSGateway_HealthCheck_FullMethodName      = "/gateway.BDNSGateway/HealthCheck"
)

// BDNSGatewayClient is the client API for BDNSGateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BDNSGateway is the gRPC service exposed by full nodes to light nodes
type BDNSGatewayClient interface {
	SubscribeHeaders(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeader], error)
	QueryDomain(ctx context.Context, in *DomainQueryRequest, opts ...grpc.CallOption) (*DomainQueryResponse, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type bDNSGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewBDNSGatewayClient(cc grpc.ClientConnInterface) BDNSGatewayClient {
	return &bDNSGatewayClient{cc}
}

func (c *bDNSGatewayClient) SubscribeHeaders(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BlockHeader], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BDNSGateway_ServiceDesc.Streams[0], BDNSGateway_SubscribeHeaders_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, BlockHeader]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BDNSGateway_SubscribeHeadersClient = grpc.ServerStreamingClient[BlockHeader]

func (c *bDNSGatewayClient) QueryDomain(ctx context.Context, in *DomainQueryRequest, opts ...grpc.CallOption) (*DomainQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainQueryResponse)
	err := c.cc.Invoke(ctx, BDNSGateway_QueryDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bDNSGatewayClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, BDNSGateway_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BDNSGatewayServer is the server API for BDNSGateway service.
// All implementations must embed UnimplementedBDNSGatewayServer
// for forward compatibility.
//
// BDNSGateway is the gRPC service exposed by full nodes to light nodes
type BDNSGatewayServer interface {
	SubscribeHeaders(*SubscribeRequest, grpc.ServerStreamingServer[BlockHeader]) error
	QueryDomain(context.Context, *DomainQueryRequest) (*DomainQueryResponse, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedBDNSGatewayServer()
}

// UnimplementedBDNSGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBDNSGatewayServer struct{}

func (UnimplementedBDNSGatewayServer) SubscribeHeaders(*SubscribeRequest, grpc.ServerStreamingServer[BlockHeader]) error {
	return status.Error(codes.Unimplemented, "method SubscribeHeaders not implemented")
}
func (UnimplementedBDNSGatewayServer) QueryDomain(context.Context, *DomainQueryRequest) (*DomainQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryDomain not implemented")
}
func (UnimplementedBDNSGatewayServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedBDNSGatewayServer) mustEmbedUnimplementedBDNSGatewayServer() {}
func (UnimplementedBDNSGatewayServer) testEmbeddedByValue()                     {}

// UnsafeBDNSGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BDNSGatewayServer will
// result in compilation errors.
type UnsafeBDNSGatewayServer interface {
	mustEmbedUnimplementedBDNSGatewayServer()
}

func RegisterBDNSGatewayServer(s grpc.ServiceRegistrar, srv BDNSGatewayServer) {
	// If the following call panics, it indicates UnimplementedBDNSGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BDNSGateway_ServiceDesc, srv)
}

func _BDNSGateway_SubscribeHeaders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BDNSGatewayServer).SubscribeHeaders(m, &grpc.GenericServerStream[SubscribeRequest, BlockHeader]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BDNSGateway_SubscribeHeadersServer = grpc.ServerStreamingServer[BlockHeader]

func _BDNSGateway_QueryDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BDNSGatewayServer).QueryDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BDNSGateway_QueryDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BDNSGatewayServer).QueryDomain(ctx, req.(*DomainQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BDNSGateway_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BDNSGatewayServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BDNSGateway_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BDNSGatewayServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BDNSGateway_ServiceDesc is the grpc.ServiceDesc for BDNSGateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BDNSGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.BDNSGateway",
	HandlerType: (*BDNSGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "QueryDomain",
			Handler:    _BDNSGateway_QueryDomain_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _BDNSGateway_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeHeaders",
			Handler:       _BDNSGateway_SubscribeHeaders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
